import {existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {chromium} from 'playwright';
import {build} from 'esbuild';
const bundle=await build({entryPoints:['tests/music-entry.js'],bundle:true,format:'iife',write:false});
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||(!existsSync(chromium.executablePath())&&process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':undefined),headless:true});
try{const p=await browser.newPage({viewport:{width:390,height:844}});p.setDefaultTimeout(60000);await p.goto(pathToFileURL(resolve('dist/index.html')).href);await p.waitForSelector('.track-row');await p.addScriptTag({content:bundle.outputFiles[0].text});const xml=await p.evaluate(()=>{const xml=window.testMusic.demoXML();return ((xml)=>{const d=new DOMParser().parseFromString(xml,'application/xml'),original=d.querySelector('part'),sp=d.querySelector('score-part').cloneNode(true);d.querySelectorAll('part,score-part').forEach(n=>n.remove());for(let i=0;i<24;i++){const part=original.cloneNode(true);part.id='P'+i;const measures=[...part.children];part.replaceChildren();for(let j=0;j<128;j++){const m=measures[j%measures.length].cloneNode(true);m.setAttribute('number',j+1);part.append(m);}const name=sp.cloneNode(true);name.id=part.id;name.querySelector('part-name').textContent='Instrument '+(i+1);d.querySelector('part-list').append(name);d.documentElement.append(part);}return new XMLSerializer().serializeToString(d);})(xml);});await p.locator('#file-input').setInputFiles({name:'large.musicxml',mimeType:'application/xml',buffer:Buffer.from(xml)});await p.locator('#confirm-import').click();await p.locator('.track-title').last().click();await p.waitForSelector('#score svg');await p.waitForFunction(()=>!document.querySelector('#score-part').disabled);assert.notEqual(await p.locator('#score-part').inputValue(),'');assert.equal(await p.locator('.measure-hit').count(),128);await p.locator('#play').click();await p.waitForFunction(()=>Number(document.querySelector('#seek').value)>0);await p.locator('#score-part').selectOption({index:24});await p.waitForFunction(()=>!document.querySelector('#score-part').disabled);assert.equal(await p.locator('.measure-hit').count(),128);assert.ok(Number(await p.locator('#seek').inputValue())>0);const height=await p.locator('#score-viewport').evaluate(e=>e.clientHeight);assert.ok(height>550);await p.screenshot({path:'test-results/mobile-large-score.png'});console.log('PASS: 24 instruments × 128 bars; compact initial part, live switching, all bar targets, score height',height);}finally{await browser.close();}
